#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
一个用于启动 ExaBayes mpirun 作业并自动生成一致性树的 Python 脚本。

最终版：
1. 会自动检查 'partitions.txt' 是否存在。
2. 如果存在，则自动生成一个“分区”的 config.nex (brlens 关联, 其他不关联)。
3. 如果不存在，则提示用户，并自动生成一个“不分区”的 config.nex。
4. 自动生成一个随机种子。
5. 根据分区情况，自动构建正确的 mpirun 命令并执行。
6. 当 ExaBayes 成功运行完毕后，自动调用 'consense' 命令生成一致性树。
"""

import subprocess
import random
import sys
import os # 导入 os 模块来检查文件是否存在

# --- 脚本配置 ---
# ExaBayes 命令将使用的文件名
PARTITION_FILE = "partitions.txt"
CONFIG_FILE = "config.nex"
PHYLOGENY_FILE = "complete.phy"
OUTPUT_PREFIX = "combine"     # ExaBayes (-n) 的输出前缀
NUM_PROCESSORS = "40"       # 您希望使用的核心数

# consense 命令的配置
CONSENSUS_OUTPUT_NAME = "myCons" # consense (-n) 的输出前缀
# ---------------------


def generate_partitioned_config(partition_file, config_file):
    """
    (情况1) 根据分区文件自动生成 ExaBayes 配置文件。
    brlens 关联 (linked)，其他参数不关联 (unlinked)。
    """
    print(f"--- 正在读取分区文件: {partition_file} ---")
    try:
        with open(partition_file, 'r') as f:
            lines = f.readlines()
            # 过滤掉空行
            partition_lines = [line for line in lines if line.strip()]
            num_partitions = len(partition_lines)

        if num_partitions == 0:
            print(f"[错误] 分区文件 '{partition_file}' 为空。")
            sys.exit(1)
            
        print(f"检测到 {num_partitions} 个分区。")

        # 1. 生成分区索引列表 (例如: ["0", "1", "2"])
        partition_indices = [str(i) for i in range(num_partitions)]
        
        # 2. 创建 "unlinked" 字符串 (格式: "(0,1,2)")
        #    根据 ExaBayes 手册 6.1 节，逗号分隔的列表用于声明独立的参数
        unlinked_str = f"({','.join(partition_indices)})"
        
        # 3. 创建 "linked" 字符串 (格式: "(0-2)")
        #    使用短横线 (-) 是关联连续范围的最简洁语法
        linked_str = f"(0-{num_partitions - 1})"

        # 4. 定义 config.nex 文件的内容模板 (包含英文注释)
        config_content = f"""#NEXUS

begin params;
  [ This config file was auto-generated by run_exabayes.py (partitioned mode) ]

  [ Model parameters (GTR+G) are unlinked across partitions ]
  [ Syntax (0,1,2) means partition 0, 1, and 2 each get a separate parameter ]
  stateFreq = {unlinked_str}
  revMat = {unlinked_str}
  ratehet = {unlinked_str}

  [ Branch lengths (brlens) are linked across all partitions ]
  [ Syntax (0-N) means partitions 0 through N share one set of branch lengths ]
  brlens = {linked_str}
end;

begin run;
    [ MCMC run parameters ]
    numGens 4000000
    numRuns 2
end;
"""
        # 5. 写入配置文件
        with open(config_file, 'w') as f:
            f.write(config_content)
            
        print(f"--- 成功生成分区配置文件: {config_file} ---")
        print(f"    > 不关联的参数 (Unlinked) 设置为: {unlinked_str}")
        print(f"    > 关联的枝长 (Linked) 设置为: {linked_str}\n")

    except Exception as e:
        print(f"\n[错误] 生成分区配置文件时发生异常: {e}")
        sys.exit(1)


def generate_unpartitioned_config(config_file):
    """
    (情况2) 为不分区的分析生成一个简单的配置文件。
    只包含 MCMC 运行参数。
    """
    print(f"--- 正在生成简单的配置文件: {config_file} ---")
    
    # 对于不分区的运行 (-m DNA)，ExaBayes 只需要知道运行参数。
    config_content = f"""#NEXUS

begin run;
    [ This config file was auto-generated by run_exabayes.py (unpartitioned mode) ]
    [ Model is specified via -m DNA on the command line ]
    numGens 2000000
    numRuns 2
end;
"""
    try:
        with open(config_file, 'w') as f:
            f.write(config_content)
        print(f"--- 成功生成不分区配置文件: {config_file} ---\n")
    except Exception as e:
        print(f"\n[错误] 生成不分区配置文件时发生异常: {e}")
        sys.exit(1)


# --- 脚本主程序 ---

# 1. 生成随机种子
random_seed = random.randint(0, 32767)

# 2. 定义 ExaBayes 命令的基础部分
base_exabayes_command = [
    "mpirun",
    "-np", NUM_PROCESSORS,
    "exabayes",
    "-f", PHYLOGENY_FILE,
    "-n", OUTPUT_PREFIX,
    "-s", str(random_seed),  # 将随机种子转为字符串
    "-c", CONFIG_FILE
]

# 3. 检查分区文件是否存在，并据此修改配置和命令
if os.path.exists(PARTITION_FILE):
    # --- 情况1: 找到分区文件 (执行分区分析) ---
    print(f"--- 找到 {PARTITION_FILE}。将按“分区”模式运行。 ---")
    generate_partitioned_config(PARTITION_FILE, CONFIG_FILE)
    
    # 添加 -q 参数 (指定分区文件)
    exabayes_command_list = base_exabayes_command + ["-q", PARTITION_FILE]
    
else:
    # --- 情况2: 未找到分区文件 (执行不分区分析) ---
    print(f"--- [提示] 未找到 {PARTITION_FILE}。将按“不分区”模式运行。 ---")
    generate_unpartitioned_config(CONFIG_FILE)
    
    # 添加 -m DNA 参数 (指定数据类型)
    exabayes_command_list = base_exabayes_command + ["-m", "DNA"]


# --- 4. 运行 ExaBayes 和 Consense ---
print("--- 准备执行 ExaBayes 分析流程 ---")

try:
    # --- 步骤 1: 运行 ExaBayes MCMC 分析 ---
    print(f"\n--- 步骤 1: 开始执行 ExaBayes MCMC 分析 ---")
    print(f"Running: {' '.join(exabayes_command_list)}")
    print("---------------------------------\n")
    
    result_mcmc = subprocess.run(exabayes_command_list, check=True, text=True)
    
    print("\n---------------------------------")
    print("--- ExaBayes MCMC 分析成功 ---")
    print("---------------------------------")

    # --- 步骤 2: 运行 Consense 生成一致性树 ---
    print(f"\n--- 步骤 2: 开始生成一致性树 (consense) ---")
    
    # 【已修正】
    # 根据您的截图，通配符必须是 "ExaBayes_topologies.run-*.{OUTPUT_PREFIX}" 格式
    topology_files_glob = f"ExaBayes_topologies.run-*.{OUTPUT_PREFIX}"
    
    consense_command_list = [
        "consense",
        "-f", topology_files_glob,
        "-n", CONSENSUS_OUTPUT_NAME
    ]
    
    print(f"Running: {' '.join(consense_command_list)}")
    result_consense = subprocess.run(consense_command_list, check=True, text=True)

    print("\n---------------------------------")
    print(f"--- 流程全部执行成功 ---")
    print(f"    > MCMC 分析已完成。")
    print(f"    > 一致性树已生成 (前缀: {CONSENSUS_OUTPUT_NAME})。")
    print("---------------------------------")

except FileNotFoundError as e:
    # e.filename 会显示是哪个命令未找到
    missing_cmd = e.filename if hasattr(e, 'filename') and e.filename else "未知命令"
    print(f"\n[错误] 命令 '{missing_cmd}' 未找到。")
    print("请确保 mpirun, exabayes 和 consense 已经正确安装并位于您的系统 PATH 路径中。")
    sys.exit(1)
    
except subprocess.CalledProcessError as e:
    # e.cmd 是一个列表，e.cmd[0] 是命令名
    failed_command = e.cmd[0]
    if failed_command == "consense":
        print(f"\n[错误] 'consense' 命令执行失败，退出码: {e.returncode}")
        print(f"MCMC 分析可能已成功，但无法生成一致性树。")
        # 【已修正】更新了错误消息中的通配符
        print(f"请检查 MCMC 输出文件 ('{topology_files_glob}') 是否存在且不为空。")
    else:
        print(f"\n[错误] 'mpirun' (ExaBayes) 命令执行失败，退出码: {e.returncode}")
        print("请检查 ExaBayes 的输出日志或错误信息。")
    sys.exit(1)
    
except KeyboardInterrupt:
    print("\n\n[用户中断] 操作已取消。")
    sys.exit(1)
    
except Exception as e:
    print(f"\n[未知错误] 发生异常: {e}")
    sys.exit(1)